import type { GradingDraftStatus, SubmissionStatus } from '@/lib/generated/prisma/enums';

/**
 * Which pile of outstanding work a submission belongs in.
 *
 * One definition, shared by the triage screen, the grading queue's filter, and the
 * per-assignment counts on a course page. Those three answer the same question and must
 * not answer it differently — a submission cannot be work to do on one screen and
 * finished on the next.
 *
 * Pure and free of imports beyond the enum types, so anything can call it.
 */

export type TriageBucket =
  | 'needs_report'
  | 'needs_manual_grade'
  | 'draft_ready'
  | 'needs_manual_review'
  | 'grading_failed'
  | 'comment_not_posted'
  | 'generating';

/**
 * The bucket, or null if the submission needs nobody.
 *
 * The set is meant to be exhaustive: every submission a student has declared finished
 * and nobody has approved belongs in one of these, so together they are the whole of
 * what stands between an instructor and being caught up. `needs_report` is usually the
 * largest — reports are generated by the instructor rather than at each push, so having
 * no report yet is the ordinary state of new work rather than an anomaly. `needs_manual_grade`
 * is the same state for an assignment the pipeline cannot grade at all.
 *
 * Decided from the most recent grading draft, not from `submission.status`. Generating a
 * report writes the draft's status and leaves the submission's alone — only approving
 * moves a submission, to GRADED — so `DRAFT_READY`, `NEEDS_MANUAL_REVIEW`, and
 * `GRADING_FAILED` are `SubmissionStatus` values that nothing ever writes. Reading them
 * would leave every bucket permanently empty.
 */
export function triageBucket(
  submissionStatus: SubmissionStatus,
  draft: { status: GradingDraftStatus } | null,
  draftIsStale: boolean,
  hasUndeliveredApproval: boolean,
  /**
   * Whether nothing about this assignment can be graded by the pipeline — a Google Doc, an
   * uploaded file, or any assignment whose sections are all manual. `isManualOnly` in
   * `lib/assignments/spec.ts` computes it from the stored row.
   */
  isManualOnly: boolean,
): TriageBucket | null {
  /*
    Checked first, and against every draft rather than the most recent one. A grade that
    was never delivered is still owed to the student whatever has happened since — and
    what happens next is usually that they push again and a new draft is generated, which
    would bury the undelivered one behind it forever.
  */
  if (hasUndeliveredApproval) return 'comment_not_posted';

  // A draft describing a commit the student has pushed past is not a report on the work
  // in front of the instructor, so it is not read here at all — the submission falls
  // through to needing a new one.
  if (draft && !draftIsStale) {
    if (draft.status === 'READY') return 'draft_ready';
    if (draft.status === 'NEEDS_MANUAL_REVIEW') return 'needs_manual_review';
    if (draft.status === 'FAILED') return 'grading_failed';
    if (draft.status === 'GENERATING') return 'generating';
  }

  /*
    Declared finished by the student and carrying no usable report. This is where work
    arrives, and where a run that generates reports for everything pending would find its
    subjects.

    A student who pushed after being graded without declaring it ready is deliberately
    not here: pushing is not asking, and their submission is still GRADED.
  */
  if (submissionStatus === 'SUBMITTED' || submissionStatus === 'RESUBMITTED') {
    /*
      The same pile of work, distinguished because the action differs and only one of them
      exists. `needs_report` offers to generate one; an assignment nothing can generate a
      report for must not show that button, and calling this work "no report yet" would
      describe it by the thing that is never going to happen to it.
    */
    return isManualOnly ? 'needs_manual_grade' : 'needs_report';
  }

  return null;
}

/** True for every bucket that counts as work remaining. A run in flight does not. */
export function isOutstanding(bucket: TriageBucket | null): boolean {
  return bucket !== null && bucket !== 'generating';
}
